merged docker and java CI

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,4 +1,4 @@
-name: Java CI
+name: Java+Docker CI
 
 on: 
   pull_request:
@@ -25,3 +25,9 @@ jobs:
       run: cd cadc-storage-adapter && gradle --info clean build javadoc checkstyleMain install
     - name: build and test cadc-storage-permissions
       run: cd cadc-storage-permissions && gradle --info clean build javadoc checkstyleMain install
+
+    - name: Build minoc
+      run: cd minoc && docker build . --file Dockerfile --tag minoc:$(date +%s)
+    - name: Build luskan
+      run: test -d luskan && (cd luskan && docker build . --file Dockerfile --tag luskan:$(date +%s)) || echo "not found"
+
